/-
End-to-end example: a left-recursive arithmetic grammar, generated by the native
LR(1) generator, validated by `isSafe` (`native_decide`), and run by the verified
interpreter. This is exactly the class of grammar (left recursion) that a PEG /
recursive-descent backend gets wrong.

    S → E eof
    E → E '+' num | num        (value = sum of the numbers)

This example demonstrates the **fully self-contained, in-Lean** path: the tables
come straight from `Grammar0.buildTables` (a `partial def`, hence not
kernel-reducible) and the safety certificate is discharged by `native_decide`
(which trusts the compiler, adding `Lean.ofReduceBool`). For the complementary
**no-compiler-trust** path — concrete emitted tables certified by kernel
`decide` — see `Examples/MiniCalc`.

LGPL-3.0-or-later (derivative of coq-menhirlib).
-/
import LeanMenhir.Generator.LR1
import Mathlib.Data.Stream.Init

namespace LeanMenhir.Examples.Arith

open LeanMenhir LeanMenhir.Gen

/-- Terminals: `num = 0`, `plus = 1`, `eof = 2`. Nonterminals: `S = 0`, `E = 1`. -/
def grammar : Grammar0 where
  numTerm := 3
  numNonterm := 2
  start := 0
  eof := 2
  prods := #[
    (0, #[.nonterm 1, .term 2]),            -- p0 : S → E eof
    (1, #[.nonterm 1, .term 1, .term 0]),   -- p1 : E → E plus num
    (1, #[.term 0])                         -- p2 : E → num
  ]

/-- The generated LR(1) tables (untrusted). -/
def tables : GenTables := grammar.buildTables

/-- Semantic actions over `Nat` (`collectArrows` supplies the popped values in
reverse-RHS order, i.e. last symbol first). -/
def actions : Nat → List Nat → Nat
  | 0, l => l.getD 1 0                 -- S → E eof   ↦ value of E
  | 1, l => l.getD 2 0 + l.getD 0 0    -- E → E + num ↦ E + num
  | 2, l => l.getD 0 0                 -- E → num     ↦ num
  | _, _ => 0

/-- The verified automaton built from the generated tables. -/
instance automaton : Automaton := automatonOfTables tables Nat actions

/-- The safety validator accepts the generated tables — checked by computation. -/
theorem isSafe_ok : Main.safeValidator (A := automaton) () = true := by native_decide

/-- The **completeness** validator also accepts the generated tables. Combined
with `Main.parse_complete`/`Main.unambiguity`, this certifies that the generated
parser recognises *every* parse tree of the grammar and is unambiguous. -/
theorem isComplete_ok : Main.completeValidator (A := automaton) () = true := by native_decide

/-- Parse a token stream (terminal index, value), ending in an infinite `eof`. -/
def parseTokens (toks : List (Fin 4 × Nat)) : Option Nat :=
  let buf : Buffer (A := automaton) := toks ++ₛ Stream'.const ((2 : Fin 4), 0)
  match Main.parse (A := automaton) (0 : Fin 1) isSafe_ok 30 buf with
  | .Parsed v _ => some v
  | _ => none

/-- `1 + 2 + 3` evaluates to `6` (left recursion handled correctly). -/
example : parseTokens [(0, 1), (1, 0), (0, 2), (1, 0), (0, 3)] = some 6 := by native_decide

/-- A single number parses to itself. -/
example : parseTokens [(0, 42)] = some 42 := by native_decide

/-- Ill-formed input (`+ 1`) is rejected. -/
example : parseTokens [(1, 0), (0, 1)] = none := by native_decide

/-- **Soundness** for the generated Arith parser (a clean corollary of
`Main.parse_correct`): whenever it returns `Parsed sem _`, `sem` is the semantics
of a real parse tree of the consumed input. -/
theorem arith_correct (logNSteps : Nat) (buffer : Buffer (A := automaton))
    (sem : automaton.symbol_semantic_type (.NT (automaton.start_nt (0 : Fin 1))))
    (bufNew : Buffer (A := automaton))
    (h : Main.parse (A := automaton) (0 : Fin 1) isSafe_ok logNSteps buffer = .Parsed sem bufNew) :
    ∃ (word : List automaton.Token) (pt : ParseTree (.NT (automaton.start_nt (0 : Fin 1))) word),
      buffer = word ++ₛ bufNew ∧ ptSem pt = sem := by
  have H := Main.parse_correct (A := automaton) (0 : Fin 1) isSafe_ok logNSteps buffer
  rw [h] at H; exact H

/-- **Completeness** for the generated Arith parser (a clean corollary of
`Main.parse_complete` specialised with the safety + completeness certificates):
*every* parse `tree` of `word`, given enough fuel (`ptSize tree ≤ 2 ^ logNSteps`),
is parsed to its own semantic value, consuming exactly `word`. -/
theorem arith_parses (logNSteps : Nat) (word : List automaton.Token)
    (bufEnd : Buffer (A := automaton))
    (tree : ParseTree (.NT (automaton.start_nt (0 : Fin 1))) word)
    (hfuel : ptSize tree ≤ 2 ^ logNSteps) :
    Main.parse (A := automaton) (0 : Fin 1) isSafe_ok logNSteps (word ++ₛ bufEnd)
      = .Parsed (ptSem tree) bufEnd := by
  have H := Main.parse_complete (A := automaton) (0 : Fin 1) isSafe_ok isComplete_ok
    logNSteps word bufEnd tree
  cases hp : Main.parse (A := automaton) (0 : Fin 1) isSafe_ok logNSteps (word ++ₛ bufEnd) with
  | Parsed sem buff => rw [hp] at H; obtain ⟨h1, h2, _⟩ := H; rw [h1, h2]
  | Timeout => rw [hp] at H; omega
  | Fail s t => rw [hp] at H; exact H.elim

/-- **Unambiguity** for the generated Arith parser: any two parse trees of the
same word have equal semantic value. -/
theorem arith_unambiguous (word : List automaton.Token)
    (tree1 tree2 : ParseTree (.NT (automaton.start_nt (0 : Fin 1))) word) :
    ptSem tree1 = ptSem tree2 :=
  Main.unambiguity (A := automaton) isSafe_ok isComplete_ok ((2 : Fin 4), 0) (0 : Fin 1)
    word tree1 tree2

end LeanMenhir.Examples.Arith
